#!/bin/bash

# Check if Script is Run as user 
if [[ $EUID -ne 0 ]]; then  
  
  git clone https://github.com/pieroproietti/get-eggs
  cd get-eggs
  sudo ./get-eggs.sh

  cd ../..
  sudo rm -R xubuntu_server_live_iso_customise

  cd $HOME 
  
  echo -ne "
---------------------------------------------------------------------------------------------------
   Now it is prepared you can modify the system or produce the ISO with eggs produce --clone  
---------------------------------------------------------------------------------------------------
"
  echo -ne "
-------------------------------------------------------------------------
                    Wait until the reboot  ...
-------------------------------------------------------------------------
"&& sleep 15
reboot

  else
    echo "You must be a non-root user to run this script, please run ./install" 2>&1
    exit 1
fi

