#!/bin/bash

util=$(getent passwd "1000"|cut -d: -f1)

systemctl mask suspend.target hibernate.target

#modif /etc/environment 
rm /etc/environment 

chown root:root config/environment
chmod 644 config/environment
mv config/environment /etc/environment

#modif /etc/sudoers
rm /etc/sudoers

chown root:root config/sudoers
chmod 440 config/sudoers
mv config/sudoers /etc/sudoers

rm /etc/lightdm/users.conf
chown root:root config/users.conf
chmod 644 config/users.conf
mv config/users.conf  /etc/lightdm/users.conf

# Lightdm Autologin 
rm /etc/lightdm/lightdm.conf
mv config/lightdm.conf /etc/lightdm/lightdm.conf

chown root:root config/lightdm.conf 
chmod 644 config/lightdm.conf 
echo "autologin-user=$util" >> /etc/lightdm/lightdm.conf

#Add policyKit (polkit) rules, allowing to use gtk root application without password
chown root:root config/disable-passwords.rules
chmod 644 config/disable-passwords.rules
mv config/disable-passwords.rules /etc/polkit-1/rules.d/disable-passwords.rules

# modif networking 
rm /etc/netplan/50-cloud-init.yaml

chown root:root config/01-network-manager-all.yaml
chmod 600 config/01-network-manager-all.yaml
mv config/01-network-manager-all.yaml /etc/netplan/01-network-manager-all.yaml

chown root:root config/nosnap
chmod 644 config/nosnap
mv config/nosnap /etc/apt/preferences.d/nosnap 

#disable networkd cause we're using NetworkManager
systemctl stop systemd-networkd.socket 
systemctl disable systemd-networkd.socket 

systemctl stop systemd-networkd.service
systemctl disable systemd-networkd.service

#Cleaning packages 
apt autoclean
apt clean
apt autoremove -y 
apt purge ~c -y 

