#!/bin/bash

# modif /etc/network/interfaces 
rm /etc/network/interfaces

chown root:root config/interfaces
chmod 644 config/interfaces
mv config/interfaces /etc/network/interfaces

#modif /etc/environment 
rm /etc/environment 

chown root:root config/environment
chmod 644 config/environment
mv config/environment /etc/environment

#modif /etc/sudoers
rm /etc/sudoers

chown root:root config/sudoers
chmod 440 config/sudoers
mv config/sudoers /etc/sudoers

# Lightdm Autologin 
rm /etc/lightdm/lightdm.conf
mv config/lightdm.conf /etc/lightdm/lightdm.conf

chown root:root config/lightdm.conf 
chmod 644 config/lightdm.conf 
echo "autologin-user=$util" >> /etc/lightdm/lightdm.conf

#Add policyKit (polkit) rules, allowing to use gtk root application without password
chown root:root config/disable-passwords.rules
chmod 644 config/disable-passwords.rules
mv config/disable-passwords.rules /etc/polkit-1/rules.d/disable-passwords.rules

#Cleaning packages 
apt autoclean
apt clean
apt autoremove -y 
apt purge ~c -y 

