#!/bin/bash

git clone https://github.com/vinceliuice/Qogir-theme.git
git clone https://github.com/vinceliuice/Tela-icon-theme.git
git clone https://github.com/milkmadedev/oreo-cursors-compiled

mkdir /usr/share/themes
mkdir /usr/share/icons 

# Installation of oreo spark cursor 
chown -R root:root oreo-cursors-compiled/oreo_spark_lime_cursors/ 
mv oreo-cursors-compiled/oreo_spark_lime_cursors/ /usr/share/icons/ 

./Qogir-theme/install.sh -c dark -d /usr/share/themes/
./Tela-icon-theme/install.sh red -d /usr/share/icons/

# Ajout icons et .desktop
rm /usr/share/applications/lshw-gtk.desktop
rm /usr/share/applications/gparted.desktop
mv desktop/* /usr/share/applications
mv icons/* /usr/share/icons 